CONNECTALDIR?=../..
S2H_INTERFACES = IntoHardware:Minp.in
H2S_INTERFACES = Minp:FromHardware

BSVFILES = Minp.bsv
CPPFILES= testMinp.cpp

CONNECTALFLAGS += -D TRACE_PORTAL

include $(CONNECTALDIR)/Makefile.connectal

