CONNECTALDIR?=../..
S2H_INTERFACES = IntoHardware:Iirfilter.in
H2S_INTERFACES = Iirfilter:FromHardware

BSVFILES = Iirfilter.bsv
CPPFILES= testfilter.cpp

CONNECTALFLAGS += -D TRACE_PORTAL

include $(CONNECTALDIR)/Makefile.connectal

